#!/bin/sh

set -e

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

pam-auth-update --package

#TODO: trigger event for uinput to pick up the new udev rule
#if command -v udevadm >/dev/null; then
#	udevadm trigger --subsystem-match=misc --sysname-match=uinput
#fi

#DEBHELPER#

exit 0
